actions/download-artifact

- .eslintignore
- .eslintrc.json
- .gitattributes
- .github/workflows/test.yml
- .gitignore
- .prettierignore
- .prettierrc.json
- README.md
- action.yml
- dist/index.js
- package-lock.json
- package.json
- src/constants.ts
- src/download-artifact.ts
- tsconfig.json
The `download-artifact` actions has been completely rewritten using typescript. The original `v1` action is a plugin written in C# that is tied to the runner. 
As part of the `v2` rewrite and to make the action more like a traditional typescript action, the core download logic has been ported over to the `@actions/artifact` package. This can be found here: https://github.com/actions/toolkit/tree/master/packages/artifact
After being in preview for over a month, we're ready to merge this into the `master` branch. Any issues that were reported in https://github.com/actions/download-artifact/issues/23 have been addressed
All the changes are largely identical to the PR that was merged into the `v2-preview` branch: https://github.com/actions/download-artifact/pull/19
I have made just a few …
> V2 Download Artifact

- README.md
- dist/index.js
- package-lock.json
- package.json
- src/constants.ts
- src/download-artifact.ts
- Update dev-dependencies so that `dependabot` security alerts go away
- The `eslint` npm package needs to be updated
- Add extra logging 
- Users get confused about the download all artifacts behavior (I've seen a few support tickets with users not fully understanding the behavior if they use `upload-artifact` without an artifact name and then `download-artifact` without a name)
- Adding extra output to make it obvious that all artifacts are being downloaded if no name is provided
- Adding extra output to make it obvious that an extra directory is created if downloading all artifacts
- Add `download-path` step output
- Will help users find out where their artifact gets downloaded to
- Updated `README` with example
- `path.resolve` is used so that if users specify something like `.`, the …
> Misc Download Artifact Improvements

- .github/workflows/test.yml
- README.md
- dist/index.js
- src/download-artifact.ts
Resolves: https://github.com/actions/download-artifact/issues/37
Upload-artifact supports basic tilde expansion using the [actions/glob](https://github.com/actions/toolkit/tree/main/packages/glob#tilde-expansion) npm package. It is also possible use tilde expansion in shell scripts on all hosted virtual environments so it logically makes sense for us to support it for `download-artifact`.
I didn't want to take a dependency on some NPM package so I copied what most packages & users do which is to replace `~` with `os.homedir`: https://stackoverflow.com/questions/21077670/expanding-resolving-in-node-js
The `README` was updated to document the new feature:
🖼 [Rendered](https://github.com/actions/download-artifact/blob/konradpabjan/tilde/README.md) 🖌
- Added extra CI test
- Local testing
- …
> Add support for tilde expansion

- README.md
- dist/index.js
- package-lock.json
- package.json
- Document Artifact Limitations 🖼 [Rendered](https://github.com/actions/download-artifact/tree/download-updates) 🖌
- Bump `@actions/artifact` from `0.3.1` to `0.3.3`
- Needed so that updated user-agent strings are used (better internal telemetry)
> Document Artifact Limitations + Bump actions/artifact package version

- .licenses/npm/@actions/core.dep.yml
- dist/index.js
- package-lock.json
- package.json
Bump `@actions/core` to v1.2.6 and then run `npm run release` to rebuild `dist/index.js`
Will close out https://github.com/actions/download-artifact/pull/62 afterwards since that doesn't update `dist/index.js`
> Bump @actions/core to v1.2.6

- .licenses/npm/@actions/artifact.dep.yml
- dist/index.js
- package-lock.json
- package.json
The PR updates the `@actions/artifact` NPM package to the latest version (0.5.0) that was recently published. Updates as part of 0.5.0 introduce some changes
- Relevant PR https://github.com/actions/toolkit/pull/675
- Will help resolve https://github.com/actions/download-artifact/issues/72
There is also a [dependabot alert](https://github.com/actions/download-artifact/security/dependabot) for the `node-fetch` NPM package. That package is dependent on the `eslint-plugin-github` package so I'm bumping up the version of just that package
> Add retries to all HTTP calls + fix dependabot alerts

- README.md
The original text implies by supplying no inputs all files are placed in the root directory without added directories by focusing only on the `path` input. In practice, supplying no inputs results in the backwards compatible `v1` behavior of creating an extra parameter. This may be obvious in some scenarios and stated somewhat later in the document, but is less obvious when the "name" matches a filename for a single file artifact.
> Clarified the `v1` and `v2` differences

- .github/workflows/codeql-analysis.yml
See https://github.com/actions/upload-artifact/pull/223.
The CodeQL run is failing for Dependabot ([example](https://github.com/actions/download-artifact/pull/97/checks?check_run_id=2803214533)):
>  Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
This is disabling the `push` trigger for Dependabot branches so they will trigger on `pull_request` instead.
> Don't trigger CodeQL on Dependabot push

- .licenses/npm/@actions/artifact.dep.yml
- dist/index.js
- package-lock.json
- package.json
v0.5.2 now considers HTTP 500 a retriable status code.  See https://github.com/actions/toolkit/pull/845.
See also https://github.com/actions/upload-artifact/pull/224.
> Ingest v0.5.2 of @actions/artifact

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation-issues.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
Adds the following issues templates:
- Bug report: template form w/ auto label
- Documentation issues: template form w/ auto label
- Feature request: template form w/ auto label
- Ask a question: link to github.community
- Security vulnerability: link to bounty.github.com
This'll help make our triage flow a bit faster.
> Add issue templates

- .licenses/npm/@actions/artifact.dep.yml
- README.md
- dist/index.js
- package-lock.json
- package.json
This change addresses [this](https://github.com/github/c2c-actions-checks/issues/270) issue.
Documentation for the semantics of `lockfileVersion` can be found [here](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion).
`lockfileVersion: 2` is corresponds to an npm `v7` (but is also backwards compatible with npm `v5` and `v6`).
> Update `lockfileVersion` in `package-lock.json`

- .devcontainer/devcontainer.json
- .github/workflows/check-dist.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/licensed.yml
- .github/workflows/test.yml
- .licenses/npm/@actions/artifact.dep.yml
- README.md
- dist/index.js
- package-lock.json
- package.json
This PR contains 4 sets of changes
- Updates `@actions/artifact` to version 1.1.1 which was released yesterday with a few bug fixes specifically for `download-artifact`. See https://github.com/actions/toolkit/blob/main/packages/artifact/RELEASES.md
- Bump `actions/checkout@v2` to `v3` in various CI workflows
- Bump `actions/setup-node@v1` to `v3` and add caching + use 16 which is what the runner now will use for all actions executions. The runner ships with it's own binary of node 12 + 16. Node 12 is going away
- Create a devcontainer so that it is easier to use codespaces off the bat. Right now if you create a codespace than it defaults to node 14 and an old NPM version which causes the lock-file version to go back down to 1 where we want to stay and the newer 2nd version
> Update to latest actions/artifact NPM package

- action.yml
Closes #153
Reference: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-docker-container-and-javascript-actions
Prevents false positives from tooling, such as `actionlint`, that depends on the metadata for static analysis.
> Add download-path output to action.yml

- action.yml
- src/download-artifact.ts
Part of https://github.com/github/actions-results-team/issues/1987
We need to ensure that download compatibility is identical between v3 and v4. This fixes v4 to ensure that there is no extra directory with the artifact name when download a single artifact. If downloading multiple artifacts at once then there is an extra directory.
See this run that compares single & multiple uploads between v3 and v4 https://github.com/bbq-beets/testing-artifacts-v4/actions/runs/6662193261
Multiple downloads:
Single download:
> [v4 beta] Fixes to download directory structure

- src/download-artifact.ts
Addresses: 
- https://github.com/actions/download-artifact/issues/262
When using pattern filters or merge multiple, it'll still log out the following:
```
No input name specified, downloading all artifacts. Extra directory with the artifact name will be created for each download
```
This adds some conditionals to the logging to be more correct.
> Clarify log messages when using `pattern` or `merge-multiple` params

- .licenses/npm/@actions/artifact.dep.yml
- package-lock.json
- package.json
We made [changes](https://github.com/actions/toolkit/pull/1648) to the `@actions/artifact` dependency so we want to update to the latest package version 2.1.1
> updating artifact dependency to version 2.1.1

- .licenses/npm/@actions/artifact.dep.yml
- .licenses/npm/@actions/core.dep.yml
- package-lock.json
- package.json
We are updating the `@actions/artifact` package to v2.1.5 to include the [archiver fix](https://github.com/actions/toolkit/commit/5a736647a123ecf8582376bdaee833fbae5b3847) and [updated error message on oidc utils.](https://github.com/actions/toolkit/commit/c5c786523e095ca3fabfc4d345e16242da34e108)
> updating `@actions/artifact` dependency to v2.1.5 and `@actions/core` to v1.0.1

- .licenses/npm/@actions/artifact.dep.yml
- package-lock.json
- package.json
We want to include the [updates](https://github.com/actions/toolkit/commit/b384fe17ba3eaae4a3ba0b3c839f328f69ac2e4c) in `@actions/artifact` from v2.1.6 in `download-artifact`.
> updating artifact package v2.1.6

- .github/workflows/test.yml
- src/download-artifact.ts
The output statements used to print download summary info & set download path output were erroneously moved to inside a loop, this change moves them back outside the loop, to ensure they are executed the correct amount of times in every case.
Closes [this issue](https://github.com/actions/download-artifact/issues/390)
> Fix bug introduced in 4.2.0

- .github/workflows/check-dist.yml
- docs/MIGRATION.md
- #401
@ramonpetgrave64 pointed out that the upload job was not defining any outputs, preventing this example from working:
https://github.com/actions/download-artifact/pull/401#discussion_r2054512579
I've updated the example to define that job output and make it clear that the upload step output is not being passed directly between jobs. I've also added some spacing for readability.
> Fix workflow example for downloading by artifact ID

- README.md
Updated documentation for download-artifact action to reflect changes in version 5.
link: https://github.com/actions/download-artifact/blob/yacaovsnc/update_readme/README.md
> Update README for download-artifact v5 changes
